#!/usr/bin/env python3
"""Generate the per-document Makefile fragment from the source manifest.

Adding a document used to mean three hand-edits to the Makefile: append the
slug to `DOCS`, add a `FETCH_SOURCE` eval, and write an explicit
`build/<slug>.toml` rule with the right source + dialect-helper prerequisites.
All three derive from facts already recorded elsewhere, so this script emits
them instead:

- `DOCS` and each doc's source files come from `download_sources.SOURCES_MANIFEST`
  (the `implemented` category, grouped by slug),
- the dialect-helper dependency (`extract/_modern.py` &c.) is read from the
  extractor's own `from ._<dialect> import …` line.

The output is `build/docs.mk`, included by the Makefile. Regenerated whenever
the manifest or any extractor changes (see the `build/docs.mk` rule).

Usage: ``python3 gen_doc_rules.py [OUTPUT]`` — writes to OUTPUT, or stdout.
"""

import re
import sys
from pathlib import Path

from download_sources import CATEGORIES, SOURCES_MANIFEST
from project import ROOT

# Source manifest keys are `<slug>_<lang>`; strip a trailing language tag to
# recover the document slug. Latin appears as both `_lt` and `_la` in the wild.
LANG_SUFFIXES = ('_en', '_lt', '_la')

# The dialect helpers a walker may lean on. Matched against the extractor's
# real import statement, not loose text mentions (e.g. a comment).
DIALECT_IMPORT = re.compile(r'^from \._(\w+) import', re.MULTILINE)
DIALECT_MODULES = {'curia', 'modern', 'oldflat'}

EXTRACT = ROOT / 'extract'


def slug_of(key: str) -> str:
    for suffix in LANG_SUFFIXES:
        if key.endswith(suffix):
            return key[: -len(suffix)]
    raise SystemExit(f'manifest key {key!r} lacks a known language suffix')


def make_escape(path: str) -> str:
    """Escape spaces for a Makefile target/prerequisite (`a b` → `a\\ b`)."""
    return path.replace(' ', '\\ ')


def dialect_deps(slug: str) -> list[str]:
    """Dialect-helper modules the extractor imports, as repo-relative paths."""
    extractor = EXTRACT / f'{slug}.py'
    if not extractor.exists():
        raise SystemExit(
            f'manifest lists implemented sources for {slug!r} but '
            f'{extractor.relative_to(ROOT)} is missing'
        )
    found = [
        name for name in DIALECT_IMPORT.findall(extractor.read_text('utf-8'))
        if name in DIALECT_MODULES
    ]
    # Stable, de-duplicated order so the generated rule is deterministic.
    seen: dict[str, None] = {}
    for name in found:
        seen.setdefault(f'extract/_{name}.py', None)
    return list(seen)


def implemented_docs() -> list[tuple[str, list]]:
    """(slug, [Source, …]) for each implemented doc, in first-seen order."""
    docs: dict[str, list] = {}
    for source in SOURCES_MANIFEST:
        if source.category != 'implemented':
            continue
        docs.setdefault(slug_of(source.key), []).append(source)
    return list(docs.items())


def render() -> str:
    docs = implemented_docs()
    out = [
        '# Generated by gen_doc_rules.py from the download_sources.py manifest.',
        '# Do not edit by hand — add a doc by adding its Source entries + an',
        '# extractor, then `make` regenerates this file.',
        '',
        'DOCS := ' + ' '.join(slug for slug, _ in docs),
        '',
        '# On-demand source fetches (every manifest category).',
    ]
    for source in SOURCES_MANIFEST:
        target = make_escape(f'sources/{source.filename}')
        out.append(f'$(eval $(call FETCH_SOURCE,{target},{source.key}))')
    out.append('')
    out.append('# Per-document TOML rules (precise source + dialect deps).')
    for slug, sources in docs:
        prereqs = [make_escape(f'sources/{s.filename}') for s in sources]
        prereqs.append(f'extract/{slug}.py')
        prereqs.extend(dialect_deps(slug))
        prereqs.append('core.py')
        out.append(f'build/{slug}.toml: ' + ' '.join(prereqs))
        out.append(f'\tpython3 parse.py {slug}')
        out.append('')
    return '\n'.join(out) + '\n'


def main() -> None:
    # A manifest category typo would silently drop docs; fail loud instead.
    bad = {s.category for s in SOURCES_MANIFEST} - set(CATEGORIES)
    if bad:
        raise SystemExit(f'unknown manifest category: {", ".join(sorted(bad))}')
    text = render()
    if len(sys.argv) > 1:
        out_path = Path(sys.argv[1])
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text, encoding='utf-8')
    else:
        sys.stdout.write(text)


if __name__ == '__main__':
    main()
